### ISSUE TITLE
Document and deliver logo artwork

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#110]
Document and deliver logo artwork.

@lovegushwa @vazquez - let's make a plan, starting with a list of assets/versions we need to create. Then, let's add those to gdrive with a link from build dot webmaker, along with basic guidelines for usage. We can keep this simple next week and then talk in Whistler about developing the system further. 

Does this sound correct? My Friday brain is fried. 

https://github.com/mozilla/webmaker-android/issues/2063

**Comment by vazquez** [comment]
Sounds good to me! :tada:

**Comment by vazquez** [comment]
Does this sound good? @xmatthewx @lovegushwa 
- [ ] Webmaker Icon
  - [ ] AI
  - [ ] SVG
  - [ ] PNG
  - [ ] High-res JPG
- [ ] Type lockup (icon with Mozilla Webmaker)
  - [ ] AI
  - [ ] SVG
  - [ ] PNG
  - [ ] High-res JPG
- [ ] Type lockup with tagline (Create. Discover. Share)
  - [ ] AI
  - [ ] SVG
  - [ ] PNG
  - [ ] High-res JPG

**Comment by xmatthewx** [comment]
I'll leave it to @cassiemc and @lovegushwa to drive this work. They probably have a better sense of the needs for marketing.

**Comment by cassiemc** [comment]
Only thing this seems to be missing is some guidelines around when / how to use. Even if they are simple, I know you guys have thought about it and we should document those thoughts. @vazquez
