### ISSUE TITLE
Thumbnails different than rendered page in app

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-desktop#111]
Stemming from https://github.com/mozilla/webmaker-android/issues/2158

Thumbnails (and renders from https://beta.webmaker.org/#/thumbnail?user=xxxxx&project=xx&page=xxx) don't accurately depict the in-app page they represent. Often, images are too big or not transformed properly.

**Comment by secretrobotron** [comment]
@k88hudson were you able to make any progress on this yesterday? Thumbnails are still pretty wrong (and often hilarious).

**Comment by k88hudson** [comment]
@secretrobotron nope, not yet

**Comment by k88hudson** [comment]
@secretrobotron any chance you could describe what you're seeing/post screenshots/thumbnails or is it hard to pin down what's going on?

**Comment by secretrobotron** [comment]
Check out the whistler scavenger hunt activity. Images are the wrong size and in the wrong position, and all of the text is squished into the center.

**Comment by xmatthewx** [comment]
See the Fire Island featured project as well.

![screenshot 2015-06-16 12 16 16](https://cloud.githubusercontent.com/assets/53411/8188076/8666b032-1421-11e5-989c-d2ad19807479.png)

**Comment by k88hudson** [comment]
Ok, I found the bug --- the transforms don't have webkit prefixes anymore.

**Comment by k88hudson** [comment]
Landing in app so we don't see regressions again: https://github.com/mozilla/webmaker-android/pull/2253

**Comment by cadecairos** [comment]
we haven't deployed this to beta.webmaker.org yet, have we?

**Comment by thisandagain** [comment]
Deployed!
