### ISSUE TITLE
Include CC-by-SA in browser-based player

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#114]
In meta data? Small text credit in footer?

**Comment by xmatthewx** [comment]
@vazquez - how could we include the CC license? small icon by title? tap to open tooltip with text and link?

**Comment by vazquez** [comment]
3 ideas:

![20150723100615900](https://cloud.githubusercontent.com/assets/1119821/8852776/16f38c22-3125-11e5-89e6-8edb271bc12f.png)

**Comment by xmatthewx** [comment]
Great. We can keep this low in the visual hierarchy. CC alone in the top-right corner is best, small with low opacity. Tooltip: 

> Full title
> by Username
> Creative Commons Attribution-ShareAlike 3.0 [link]

**Comment by xmatthewx** [comment]
@vazquez - when UI is done, let's open the build ticket in -core repo.

**Comment by vazquez** [comment]
@xmatthewx - What do you think?

![screenshot 2015-07-24 11 37 29](https://cloud.githubusercontent.com/assets/1119821/8878327/67781338-31f8-11e5-8c0a-bc60cc135d86.png)

**Comment by xmatthewx** [comment]
The (CC) looks good. Still wonder if this will overwhelm a mobile browser view and wonder if it show float in the bottom right corner. The tooltip content probably won't fit over the header bar. Are there 3 type sizes in there or two? Let's do two.  

Without pixel perfection, let's try a few more various mocks that show this in context.

**Comment by vazquez** [comment]
2 font sizes being used, but I will work on showing this tooltip in different views

**Comment by vazquez** [comment]
@xmatthewx - Check this out.

#### Desktop Player

<img width="386" alt="screenshot 2015-07-24 13 22 22" src="https://cloud.githubusercontent.com/assets/1119821/8880483/27756c7c-3207-11e5-9f68-e53d60f1451f.png">

#### Mobile Web Player

<img width="541" alt="screenshot 2015-07-24 13 22 06" src="https://cloud.githubusercontent.com/assets/1119821/8880488/2e0a931e-3207-11e5-801b-60a7498a36eb.png">

What dost thou think?

**Comment by xmatthewx** [comment]
The (CC) style and position is looking good. Rework the pop-out as discussed.

**Comment by xmatthewx** [comment]
If the team wants to pull this into Android, I recommend that we only show it on the project map view, not the page view.

**Comment by vazquez** [comment]
@xmatthewx - I tried grey and purple but they were far too dominant. However, I modified the aeshetic and position of the bubble to be conformant to the design language we established.

#### Desktop Player

##### Before Hover

![screenshot 2015-07-24 14 53 42](https://cloud.githubusercontent.com/assets/1119821/8882290/d76a4bb4-3213-11e5-908f-a560d33e0ea2.png)

##### On Hover

![screenshot 2015-07-24 14 53 54](https://cloud.githubusercontent.com/assets/1119821/8882294/dc81a016-3213-11e5-8bef-71311f15149d.png)

---

#### Mobile Web

##### Before Tap

![screenshot 2015-07-24 14 59 34](https://cloud.githubusercontent.com/assets/1119821/8882411/a84a14ee-3214-11e5-8ffd-caab1a590608.png)

##### On Tap

![screenshot 2015-07-24 14 59 43](https://cloud.githubusercontent.com/assets/1119821/8882417/b003f362-3214-11e5-972f-56550d74cd8b.png)

**Comment by xmatthewx** [comment]
I like the new style. I wonder if the baseline should align between link and 'CC' rather than the circle. Your call .

**Comment by vazquez** [comment]
Updated the design and opened implementation issue https://github.com/mozilla/webmaker-core/issues/414
