### ISSUE TITLE
Non-ASCII characters show up as empty squares in thumbnails

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-desktop#115]
When non-ASCII characters (or Bangla, at least) appears on the screen that's used in a thumbnail, text appears as squares:

![https://dgu16gle6my6q.cloudfront.net/mobile-center-cropped/small/webmaker-desktop/aHR0cHM6Ly9iZXRhLndlYm1ha2VyLm9yZy8jL3RodW1ibmFpbD91c2VyPTQyNTA2NCZwcm9qZWN0PTQ1JnBhZ2U9MTk0](https://dgu16gle6my6q.cloudfront.net/mobile-center-cropped/small/webmaker-desktop/aHR0cHM6Ly9iZXRhLndlYm1ha2VyLm9yZy8jL3RodW1ibmFpbD91c2VyPTQyNTA2NCZwcm9qZWN0PTQ1JnBhZ2U9MTk0)

cc @jbuck @thisandagain @cadecairos @k88hudson

**Comment by cadecairos** [comment]
I'm not sure how much we can do here. [This is the url used to render the project](https://beta.webmaker.org/#/thumbnail?user=425064&project=45&page=194) 

It loads find in my browser. I think the PhantomJS system used by blitline might not be able to handle those characters.

Are we loading in fonts?

**Comment by jbuck** [comment]
Here's a sample screenshot URL to pass around: https://d5bds2ubg5m9p.cloudfront.net/mobile-center-cropped/small/webmaker-desktop/aHR0cHM6Ly9iZXRhLndlYm1ha2VyLm9yZy8jL3RodW1ibmFpbD91c2VyPTQyNTA2NCZwcm9qZWN0PTQ1JnBhZ2U9MTk0JnQ9MTQzNDM5MDU2ODEwNA==

I've contacted Blitline support, I'll let you know when I hear back. Lets assume the answer is "We can't fix this." Do we wontfix, or come up with another solution?

**Comment by thisandagain** [comment]
This certainly needs a fix of some kind. I'm not super sure what our options are besides "replace blitline" ... @simonwex thoughts?

**Comment by jbuck** [comment]
Response from Blitline:

> Indeed it looks like there are some Unicode characters our underlying library (PhantomJS 2.0) can’t render properly in a screenshot. I’ve attached a screenshot of a bunch of different unicode languages and scripts generated with PhantomJS. As you can see there are a number that are not redered properly.
> 
> I will do a quick check to see if there is something we can do to support some of the ones that aren’t support, but chances are we will have to wait until PhantomJS supports this functionality in it’s headless browser.
> 
> [unicode_examples](https://cloud.githubusercontent.com/assets/578466/8168818/a58035e6-1373-11e5-8494-6ac693668cc2.png)

They also attached a Blitline screenshot of a UTF8 examples page. If you look at number 104 you'll see that it doesn't render Bengali there

**Comment by jbuck** [comment]
@thisandagain And if we do replace Blitline, we'd also need to replace PhantomJS 2.0 :/

**Comment by jbuck** [comment]
@thisandagain Good news! Chris is able to render Bengali text on his local copy of PhantomJS, so PhantomJS is definitely capable of doing it, we just need to figure out what library on his system makes that possible. Here's hoping it's an easy to install font package...

**Comment by thisandagain** [comment]
\o/

**Comment by jbuck** [comment]
Update: Blitline was able to make a change to their configuration that allowed for Bengali script to work: ![bengali](http://dev.blitline.s3.amazonaws.com/2012031612/XVBsG4FNFO5eIJkyEyzHgw/47DYDk_cy6zSPr_PhJ5RtHA.jpg)

When Blitline has rolled out this change to their service, I'll update this bug and then we can regenerate the thumbnails.

**Comment by davidascher** [comment]
Nice

**Comment by jbuck** [comment]
Blitline has rolled out this change:

![](https://dgu16gle6my6q.cloudfront.net/mobile-center-cropped/small/webmaker-desktop/aHR0cHM6Ly9iZXRhLndlYm1ha2VyLm9yZy8jL3RodW1ibmFpbD91c2VyPTQyNTA2NCZwcm9qZWN0PTQ1JnBhZ2U9MTk0JnQ9MTQzNDQ3OTgxNDUxNg==)

 :tada:

**Comment by k88hudson** [comment]
Thanks for getting this resolved, great work everyone +++

**Comment by k88hudson** [comment]
Also... you made Blitline better for everyone ^_^
