### ISSUE TITLE
Lots of empty thumbnails

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-desktop#123]
Looking at incoming content today, and noticed that many missing thumbnails. Taking a peek at the database, lots of projects that were created minutes, hours, or days ago still have `{"320":""}` or just `{}` in their `thumbnail` column (don't understand the difference there either).

I wrote a script to count the number of missing thumbnails on each page of 100 projects from `api.webmaker.org/projects`:

```
0: 54 / 100 = 54%
1: 46 / 100 = 46%
2: 54 / 100 = 54%
3: 55 / 100 = 55.00000000000001%
4: 48 / 100 = 48%
5: 58 / 100 = 57.99999999999999%
6: 46 / 100 = 46%
7: 45 / 100 = 45%
```

~Consistently, 50% of projects don't have thumbnails.

I wrote a more complex script to check various details of each project (does it have more than one page? does it have any elements?):

```
0: 23%
1: 20%
2: 19%
3: 19%
4: 18%
5: 22%
6: 17%
7: 12%
```

Much lower. But, still not insignificant.

What's the scoop? Is our server not producing thumbnails from requests dependably?

Side question: are lots of people not bothering to create enough to trigger a thumbnail to be generated?

cc @thisandagain @jbuck

**Comment by jbuck** [comment]
@secretrobotron do you think you could provide one more datapoint and look at the date/time distribution of projects that have thumbnails?

**Comment by jbuck** [comment]
![n1bn3](https://cloud.githubusercontent.com/assets/578466/8216692/250e91ac-1506-11e5-919b-13b829c2c224.jpg)

Here's how this bug goes down:
1) Create a new project, and edit the default page 
2) Save the page with the back button
3) Click the edit page button again
4) Edit the page to show something different
5) Save the page with the back button
6) Visit the "Makes" screen. Notice that your thumbnail is blank or shows the content from step 2.

What's happening is that when the api saves the project updates in step 2 is it sends `"thumbnail": {"320":""}` in the response to the client, and waits until the request has ended to send the screenshot generation request and save it in the db. Basically the client is clobbering the thumbnail.
