### ISSUE TITLE
Test browser player on mobile and desktop

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#124]
Support matrix:
- [ ] Desktop
  - [ ] Chrome (latest - 1)
  - [ ] Firefox (latest - 1)
  - [ ] Safari (latest - 1)
- [ ] Android
  - [ ] Chrome (latest)
  - [ ] Firefox (latest)
  - [ ] Android browser (4.4+)
- [ ] iOS
  - [ ] Chrome (latest)
  - [ ] Safari (latest)

**Comment by thisandagain** [comment]
Added support matrix above ^^

**Comment by xmatthewx** [comment]
Keep in mind that mobile is p1, desktop p2. 

cc @toolness

**Comment by xmatthewx** [comment]
QA - viewing projects in the browser. @flukeout @secretrobotron - edits or additions?
- Browser
  - What's your browser? OS? Device?
- Page
  - [ ] page is visible and centered
  - [ ] page elements appear with layout as expected 
- Page navigation
  - [ ] neighboring pages are visible with minimal opacity
  - [ ] navigation arrows are positioned correctly and point toward neighboring pages
  - [ ] tap an arrow to navigate to a neighboring page
  - [ ] view transitions smoothly with correct page, neighbors, and arrows
- Button links
  - [ ] find a page with button. tap it to navigate to another page
  - [ ] page transitions smoothly with correct page, neighbors, and arrows
- Header
  - [ ] project title and author appears aligned left, truncated with ellipsis (...) if necessary
  - [ ] tap the Webmaker logo to visit the website
- Get the app
  - [ ] "get the app" appears (desktop & tablet only)
  - [ ] tap app button to load play store page
  - [ ] text is localized properly

**Comment by xmatthewx** [comment]
Moving to https://github.com/mozilla/webmaker-core/issues/16
