### ISSUE TITLE
Build promo component for Maker Party

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#129]
Build a component for cross promotion on Webmaker. 
- styles should be written according to style guide (#79)
- launch with artwork specific to Maker Party (https://github.com/mozilla/teach.webmaker.org/issues/737)
- load component above footer in splash.jsx

**Comment by hannahkane** [comment]
@xmatthewx - would you mind putting this in the next milestone and assigning it to @mmmavis, please? (I don't have privs to do that)

**Comment by mmmavis** [comment]
Helllllo, 

I'm happy to take this on but just wanna flag the next heartbeat will be extra short for me (2 work days, July 29-30) due to Whistler workweek, July 1st Canada Day, and my tentative PTO July 2-3. 

@hannahkane I would need your help on prioritizing tickets for me for the next heartbeat :wink: Thanks!

**Comment by hannahkane** [comment]
thanks, @mmmavis. This will definitely be a priority, even if it means putting nothing else in the heartbeat. Thanks!

**Comment by mmmavis** [comment]
Hellllllllllllo @xmatthewx ,

I'm gonna to work on this today.  I read through https://github.com/mozilla/teach.webmaker.org/issues/737 and https://github.com/mozilla/webmaker-desktop/issues/79 but I'm still unsure which mockup I should follow - in specific, I can't tell what background color I should set for that promo section.

I talked to @sabrinang just now and she said using [Viking Yellow](https://cloud.githubusercontent.com/assets/2492510/8196418/b1d42b40-1440-11e5-8e36-f58abf28e119.png) is fine.  How does that sound for you?

Mavis

**Comment by mmmavis** [comment]
Also, I assume I'm just adding a _new_ section to the existing splash page(off of `develop` branch) and leaving the rest of the copy/UI unchanged?  :eyes:  (Was trying to compare between what's on the PROD site, the `develop` branch, and the mockup)

**Comment by xmatthewx** [comment]
I trust the guidelines and @sabrinang's choices. Lookin' good. 

Regarding the build: 
- Everything currently in splash.jsx should remain unchanged. 
- You'll add this promo there above the footer in the develop branch.  
- It'd be great to include this as a separate component like the footer. I bet @gvn could lend a hand setting that up if it's not obvious.

Also, helllllllllllo back at you.

**Comment by mmmavis** [comment]
gotcha! :+1:

**Comment by mmmavis** [comment]
Heyyy @vazquez 

(though I know you are on PTO today and I'll probably see you at dinner tonight...)
[Your earlier comment](https://github.com/mozilla/teach.webmaker.org/issues/737#issuecomment-113260411) suggested to add code in `splash.jsx` and `splash.less` but I think having a separate `<Promo>` component like what @xmatthewx suggested  (`components/promo/promo.jsx` and `components/promo/promo.less`) would make it easier for us to add _any_ promo banner in the future.  :bowtie: I'll have a PR ready soon. Free feel to make comments and suggestion on that :dancer:

**Comment by hannahkane** [comment]
Is there an estimate on when this will be released? Thanks!

**Comment by mmmavis** [comment]
Auto deploy is broken due to repo renaming.  Waiting for a R+ on https://github.com/mozilla/webmaker-browser/pull/142 and we should be able to verify the promo banner on staging soon.

**Comment by thisandagain** [comment]
So sorry about that @mmmavis ... thanks for the patch. Landed in staging and pending travis build for production.

**Comment by mmmavis** [comment]
no problem at all.  this means i got to know more about this repo :smile:

**Comment by mmmavis** [comment]
wow it's up on https://beta.webmaker.org/#/ !!! (that was fast)

cc @hannahkane

**Comment by hannahkane** [comment]
Looks pretty. :)

**Comment by xmatthewx** [comment]
Agreed. :+1:  Implementation looks great on staging.

**Comment by vazquez** [comment]
Looking sweet @mmmavis!

On Thursday, July 2, 2015, matthew w notifications@github.com wrote:

> Agreed. [image: :+1:] Implementation looks great on staging.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/webmaker-browser/issues/129#issuecomment-118175018
> .

## 

Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez http://twitter.com/iamrvazquez
IRC: ricardo
