### ISSUE TITLE
Outline Webmaker animation

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#14]
The new unified Webmaker product needs an animated pitch. 

First step: outline 30-60 second spot
Deliverable: slide deck

cc @HPaulJohnson

**Comment by thisandagain** [comment]
Feels weird to position this as a "commercial". We just need a quick animation to help communicate the intent of the product while we are in development. This helps when we are talking to partners and gives an overall impression of the quality and positioning of the app.

See https://vimeo.com/101748208 for reference. This was built a couple weeks into the design process of WMA and helped get folks on board.

**Comment by HPaulJohnson** [comment]
Thanks for clarifying "commercial." @xmatthewx happy to jump in and help with this. I'm out the rest of the week but will connect with you on Monday to discuss.

**Comment by xmatthewx** [comment]
tracking in https://github.com/mozilla/webmaker-app/issues/1456
