### ISSUE TITLE
Add analytics to Maker Party promo

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#144]
We have a new promotional component on https://beta.webmaker.org/. Significant traffic will arrive soon. Do we have event tracking in place for this campaign? 

@mmmavis @adamlofting @hannahkane @secretrobotron

**Comment by adamlofting** [comment]
What do we want to track? I'm guessing just number of clicks out to the Maker Party site?

The simplest solution is to update the target URL of the link to include some parameters unique to this landing page: 
- https://teach.mozilla.org/events/?ref=beta.webmaker.org

That will make this traffic easy to identify in the teach.m.o stats.

**Comment by hannahkane** [comment]
I can't add an assignee, but hoping @mmmavis can get to this today.
