### ISSUE TITLE
Point vanity URLs at webmaker.org and track hits

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-desktop#146]
We'd like to give out some short vanity URLs that point at webmaker.org, but use them for tracking. e.g. A poster might have /discover, and a twitter link might have /create, and we want to see what kind of return we get from each.

So far, we've just split them up by region, but maybe we can come up with more to track individual marketing mechanisms.
BD: http://webmaker.org/discover
BR: http://webmaker.org/create
ID: http://webmaker.org/share
KE: http://webmaker.org/imagine
North America: http://webmaker.org/make

cc @hpauljohnson

**Comment by xmatthewx** [comment]
Would we use /discover and /make for the browser-based platform itself?

**Comment by secretrobotron** [comment]
Yeah, almost certainly. Might need a different convention. I just took the mzl.la links we already have as an example.

**Comment by xmatthewx** [comment]
tracking in https://github.com/mozilla/webmaker-launch/issues/98
