### ISSUE TITLE
On windows, 'npm start' doesn't work

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-desktop#151]
I'm using npm 2.10.1 and node 0.12.4, and after cloning and running `npm install`, `npm start` does the following:

```
[Atul:~/Documents/mozilla/webmaker-browser]$ npm start

> webmaker-desktop@1.0.0 start c:\Users\Atul\Documents\mozilla\webmaker-browser
> npm run build && npm run server


> webmaker-desktop@1.0.0 build c:\Users\Atul\Documents\mozilla\webmaker-browser
> npm-run-all build:**


> webmaker-desktop@1.0.0 build:clean c:\Users\Atul\Documents\mozilla\webmaker-browser
> rimraf ./build && mkdirp ./build


> webmaker-desktop@1.0.0 build:static c:\Users\Atul\Documents\mozilla\webmaker-browser
> ncp ./static ./build


> webmaker-desktop@1.0.0 build:css c:\Users\Atul\Documents\mozilla\webmaker-browser
> npm run watch:css -- --no-watch


> webmaker-desktop@1.0.0 watch:css c:\Users\Atul\Documents\mozilla\webmaker-browser
> autoless --autoprefix "> 5%, last 2 versions, android >= 4.0" ./src ./build/css "--no-watch"

Finding files...
o src\colors.less
o src\components\promo\promo.less
o src\pages\error\error.less
o src\pages\legal\legal.less
o src\pages\player\player.less
o src\pages\project\project.less
o src\pages\splash\splash.less
o src\pages\thumbnail\thumbnail.less
√ src\main.less -> build\css\main.css

> webmaker-desktop@1.0.0 build:js c:\Users\Atul\Documents\mozilla\webmaker-browser
> npm run build:core && npm run config && webpack


> webmaker-desktop@1.0.0 build:core c:\Users\Atul\Documents\mozilla\webmaker-browser
> npm explore webmaker-core -- npm install && node npm_tasks/copy-env.js && npm
explore webmaker-core -- npm run build

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

c:\Users\Atul\Documents\mozilla\webmaker-browser\node_modules\webmaker-core>

```

At this point it _looks_ like I'm at a `cmd.exe` prompt (which is weird since I was in a `bash` shell before), but typing does nothing. I can press Ctrl-C twice to get back to my bash shell.

**Comment by toolness** [comment]
So I guess the offending code is in `package.json`'s `build:core` task:

```
npm explore webmaker-core -- npm install && node npm_tasks/copy-env.js && npm explore webmaker-core -- npm run build
```

One solution might be to add a `postinstall` step to `webmaker-core`'s `package.json` that just calls `npm run build`. I'm not entirely sure what the purpose of running `node npm_tasks/copy-env.js` is, though, or why it should have anything to do with the `npm run build` step of a dependency...

**Comment by Pomax** [comment]
cc @gvn, I'll try to install this today on my windows machine and see what's going wrong =(

**Comment by gvn** [comment]
Thanks @Pomax !

**Comment by Pomax** [comment]
Looks like `npm explore` is doing really weird things and we probably don't want to make use of it. What is its role in the `npm start` script?

**Comment by Pomax** [comment]
looks like `npm explore` is the culprit: what are we using it for?

**Comment by gvn** [comment]
`npm explore` is used to run `webmaker-core`'s build script.

**Comment by toolness** [comment]
We discussed [using `postinstall` instead of `npm explore`](https://github.com/mozilla/webmaker-browser/issues/151#issuecomment-120899409) in today's stand and people seemed in favor of it, so that's another alternative here that I'm interested in.

**Comment by gvn** [comment]
Do post install commands run for dependencies though?

**Comment by gvn** [comment]
Dammit...didn't mean to close.

**Comment by toolness** [comment]
Hmmmm good question--I had assumed they did, but now I'm not sure...

**Comment by gvn** [comment]
Also, do we really want to have to run `npm install` every time we want to build core?

**Comment by ryanwarsaw** [comment]
@gvn If it can be avoided, I most definitely think removing that would be a good idea.

**Comment by Pomax** [comment]
`npm install` is a one time operation. It should not be necessary to effect a build.

**Comment by gvn** [comment]
@ryanw-se Can you clarify what you're referring to?

**Comment by ryanwarsaw** [comment]
@gvn "Also, do we really want to have to run `npm install` every time we want to build core?"

**Comment by toolness** [comment]
Yeah, in terms of _re_-building core for development purposes, we definitely shouldn't have to re-run `npm install` or anything like that. Makes me think that exposing `webmaker-core`'s build system via an API--or, as @thisandagain suggested a while back, a CLI--might be a better solution, but I don't think I understand the context well enough to make a good recommendation...

**Comment by Pomax** [comment]
As alternative to `npm explore`, could we give webmaker-core a `bin` script instead, so we can just run it as an npm command like any other package?

**Comment by toolness** [comment]
Yeah, I think a `bin` script is the most straightforward solution... Keeps everything working basically the same way it's already working, but makes things work on windows.

**Comment by gvn** [comment]
@Pomax I think that's a good approach to explore. I used explore as a shortcut to writing my own CLI/bin scripts.

**Comment by gvn** [comment]
Essentially npm explore should be doing the same thing as a bin script would (running some shell commands), but if it doesn't let's try rolling a CLI.

**Comment by Pomax** [comment]
yeah I think I'll file a bug on this over on the npm repo too. `explore` is definitely not doing what it should be doing.

**Comment by Pomax** [comment]
filed https://github.com/npm/npm/issues/8932 to make the npm folks aware of this problem.
