### ISSUE TITLE
Post new Terms of Service

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#152]
New Terms of service should be posted in advance of an upcoming announcement. https://beta.webmaker.org/#/legal
- At top:  "New terms of service go into effect on July XX, 2015" where xx = 27th ??
- Old terms should remain below. Maybe with link at the top "Current terms"
- You could handle these as two pages, but probably easier as one.

cc @hpauljohnson @KevZawacki

draft in gdrive "Webmaker - t.m.o. TOS - Draft 7-2-15"

**Comment by xmatthewx** [comment]
Looks like we are ready to post the terms. 

Add this statement to the top of the page: 

> "Below are the new terms of service for Webmaker and Mozilla Learning 
> Networks, which will go into effect July 27, 2015"

On the 27th, this line would go away.

**Comment by mmmavis** [comment]
@xmatthewx where can I look for copy for the _new_ Terms of Service? Or it has been pushed live?

**Comment by HPaulJohnson** [comment]
I just want to make sure we don't push this live until we resolve some of the questions in the related comms ticket, https://github.com/mozilla/webmaker-launch/issues/90

**Comment by xmatthewx** [comment]
Roger that. @mmmavis - follow @HPaulJohnson's lead on this bit.

**Comment by xmatthewx** [comment]
Ok. Terms are posted and ready. Footer still links to current terms. Closing this and will file a bug to update the footer when the day arrives.
