### ISSUE TITLE
Link to a specific version or hash of webmaker-core

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-desktop#155]
Currently our package.json just links to https://github.com/mozilla/webmaker-core.git, but I'm concerned that this could cause problems. For example, in #153 I issued a PR that worked fine for me, but didn't for @gvn because he was using a slightly newer version of `webmaker-core` than me. It was impossible for me to figure out exactly what version of `webmaker-core` he was using without asking him (I happened to just update my `webmaker-core` to the latest revision, which reproduced the problem he was getting, but this might not have been the case if the software were being developed more quickly or something).

Anyways, there's all kinds of weird situations this could lead to, e.g. if webmaker-core is updated and accidentally breaks webmaker-browser but not webmaker-android, and so on. Having the dependents tie themselves to a specific version of the dependency is useful for all the same reasons it's useful for our other third-party dependencies.

**Comment by gvn** [comment]
Locking to a version would work from an ops perspective, but not from a development one. Typically we're going to be running and editing the core locally and working simultaneously on one or more platforms that consume it.

We need to think of core as a service and not a library. Always expect that you have to use the latest version. We all have to be conscious of how changes to core may affect the platforms (and test accordingly!).

**Comment by toolness** [comment]
I think it's a good idea to think of core as a service, but that still means that we can bust up versioning!

For instance, as per [semver](http://semver.org/) we can only change the **major** version number when we make incompatible API changes, and then in our `package.json` we could specify that we just require e.g. version `^2.0.0` (note the use of the [caret](http://stackoverflow.com/a/22345808)) to ensure that we're using the latest minor version of API v2.

There's a few things I like about this approach:
- It encourages us to have a **documented**, outward-facing API
- It encourages us to [keep a changelog](http://keepachangelog.com/)
- It encourages us to think about how our code changes to webmaker-core will affect _all_ consumers of it, not just whichever one we happen to be working on (right now it's not _that_ hard to do this since we only have 2 consumers, but this is going to get harder in the future)

Anyhow, it does potentially slow down development speed, but due to the fact that we've got multiple consumers of this module, I'm concerned that it might be necessary in order to avoid technical debt. I could be totes mistaken though.

**Comment by gvn** [comment]
CC @k88hudson

**Comment by gvn** [comment]
Ok, after thinking more about this, you're totally right. We should start versioning/tagging core and specifying a version in the platform manifests.

npm link is definitely viable for local simultaneous development.

**Comment by xmatthewx** [comment]
Tracking here: https://github.com/mozilla/webmaker-core/issues/384
