### ISSUE TITLE
Find or create a project specifically for QA

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#174]
Let's identify a good project for QA. Share URL and screenshots here: #124 

should include: 
- multiple pages
- page layout along 2-axis
- mix of photos and text
- functioning button(s)

**Comment by secretrobotron** [comment]
Try these:
- https://beta.webmaker.org/users/172138/projects/3709
- https://beta.webmaker.org/users/446905/projects/4072
- https://beta.webmaker.org/users/448373/projects/4089
- https://beta.webmaker.org/users/431001/projects/1103

**Comment by secretrobotron** [comment]
<img width="1440" alt="screenshot 2015-07-16 14 58 25" src="https://cloud.githubusercontent.com/assets/403231/8732379/269bfa60-2bcb-11e5-8bad-77cd7fa98a50.png">
<img width="1440" alt="screenshot 2015-07-16 14 58 27" src="https://cloud.githubusercontent.com/assets/403231/8732380/269fbca4-2bcb-11e5-832b-ff9c5486ba1b.png">
<img width="1440" alt="screenshot 2015-07-16 14 58 29" src="https://cloud.githubusercontent.com/assets/403231/8732381/26a1d23c-2bcb-11e5-953b-89b8560255c1.png">
<img width="1440" alt="screenshot 2015-07-16 14 58 33" src="https://cloud.githubusercontent.com/assets/403231/8732382/26a3431a-2bcb-11e5-83e0-d7d1a34d6b8b.png">

**Comment by xmatthewx** [comment]
success. links heres: https://github.com/mozilla/webmaker-core/issues/16#issuecomment-122429779
