### ISSUE TITLE
Migrate URL redirects from wm.org to beta site

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#177]
@jbuck said:

> The existing redirects can be found in https://github.com/mozilla/webmaker.org/blob/a5c8b8eb18a3e6e494443f41bee33d11602344dd/routes/redirect.js

@mmmavis - is this something you can handle?

**Comment by mmmavis** [comment]
hey @xmatthewx what's the context of this? :grin: Is it something we should have in place before July 27th or after(for the **new** webmaker.org)?

**Comment by xmatthewx** [comment]
Any redirects should continue to work when we launch the new site. As an example, /party redirects to teach.mozilla.org/events. We don't want to lose that.

**Comment by mmmavis** [comment]
cool gotcha! I assume many of them will be redirected to old.webmaker.org?

**Comment by xmatthewx** [comment]
Yes. We will probably also need to add a few more to preserve top destinations. Filed separately:   https://github.com/mozilla/webmaker.org/issues/1423

**Comment by mmmavis** [comment]
Obsoleted. Closing.
