### ISSUE TITLE
Make something with future Webmaker

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#18]
@cassiemc @flukeout @iamjessklein @vazquez @sabrinang  (also @ScottDowne @LauraReynal  @secretrobotron )

As we plug along with the new Webmaker platform, we have some ideas of what somebody _might_ make. I'm curious -- what would you _actually_ make?
- Step 1 - Think of something you'd like to make & share with a real person in your life.
- Step 2 - Make the tiles using either [PicCollage](http://pic-collage.com/) (mobile), [Newhive](http://newhive.com/) (desktop), or similar. 
- Step 3 - Make an aerial view (can show tile preview or color only).

Pretend that each thing you make is a linkable tile. Stay within the features listed here: https://github.com/mozilla/webmaker-desktop/issues/16#issuecomment-83719288.

Make sense? Good idea? Suggestions to improve this exercise? 

Post your results below. Due next Friday?

**Comment by xmatthewx** [comment]
on newhive you can add your things to a collection so that people can use arrows to nav between them like tiles. http://newhive.com/nicholasobri/hollow-valley-19?q=%23hollowvalley

**Comment by iamjessklein** [comment]
Is this what you mean @xmatthewx ?

I imagine dropping my progress into each tile for a project over the course of the day and sharing it with my colleagues:

![img_3753](https://cloud.githubusercontent.com/assets/535012/6790678/beffb284-d17f-11e4-9416-628bd643bca7.JPG)

**Comment by xmatthewx** [comment]
Thanks @iamjessklein. This is a good example of something you _could_ share with tiles, but would you? What does tiles offer that you couldn't accomplish with github or email or the blogpost that you actually wrote on this topic? (These questions are to challenge all of us, not you on this particular idea.)

**Comment by xmatthewx** [comment]
Here's an example project. 
- lo-fi demo: http://jsbin.com/yoqici
- zip of pages: https://www.dropbox.com/s/0eqrnyhapt86v3y/atkins.zip?dl=0
- preview: 

![anna_atkins](https://cloud.githubusercontent.com/assets/53411/7077003/69c227de-dedb-11e4-972b-621e98c39f71.jpg)

**Comment by xmatthewx** [comment]
Closing. @secretrobotron will open new issues around content development. 

demo of example projects:
- http://flukeout.com/examples/tiles-nav-2/?project=yams
- http://flukeout.com/examples/tiles-nav-2/?project=atkins
