### ISSUE TITLE
Fix links and terms

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#184]
A few mistakes found their way into production. Here's a plan for a relatively easy, quick fix: 
- footer on beta site
  - [ ] point "privacy" link to: https://www.mozilla.org/en-US/privacy/websites/
  - [ ] point "legal" link to: https://webmaker.org/en-US/terms
  - we will redirect "legal" to the new terms page on beta when they go into effect
- legal terms page on beta site
  - [ ] add to the top "Below are the new terms of service for Webmaker and Mozilla Learning 
    Networks, which will go into effect July 27, 2015"
  - note: nothing should link here until terms are finalized and announced

**Comment by mmmavis** [comment]
@xmatthewx 

> - footer
>   - [ ] point "privacy" link to: https://www.mozilla.org/en-US/privacy/websites/
>   - [ ] point "legal" link to: https://webmaker.org/en-US/terms

is this an interim solution? just wondering if I should delete [the view code](https://github.com/mozilla/webmaker-browser/tree/develop/src/pages/legal) from this repo

> - legal terms page
>   - [ ] add to the top "Below are the new terms of service for Webmaker and Mozilla Learning 
>     Networks, which will go into effect July 27, 2015"

Which page are we talking about here? the current one on beta.webmaker.org OR the one on webmaker.org?

> - note: nothing should link here until terms are finalized and announced

sorry, which page is this?  :grin:

**Comment by mmmavis** [comment]
@xmatthewx nvm I think I'll remove them to keep the codebase clean.  If we ever need them back I can always grab them from commit history :wink:

**Comment by xmatthewx** [comment]
Edited my comment above to clarify.
