### ISSUE TITLE
Redirect beta project URLs to new wm.org

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#196]
current project viewer URL: https://beta.webmaker.org/#/player?user=446905&project=4072
current share URL: https://beta.webmaker.org/#/project?user=446905&project=4072

cc @secretrobotron

**Comment by mmmavis** [comment]
@secretrobotron @xmatthewx 

Hey sorry I'm not very familiar with things in the Webmaker world. Could you guys fill me with a bit more details?  I assume the `/player` and `/project` paths are relative to its root, e.g., they would continue to work after we change the domain from `beta.webmaker.org` to `webmaker.org`?

**Comment by xmatthewx** [comment]
@secretrobotron - If you think that prior URLs are fairly disposable, we can just close this.

**Comment by xmatthewx** [comment]
@mmmavis - I'm going to reassign to @jbuck to handle this via DNS if need it.

**Comment by xmatthewx** [comment]
resolved
