### ISSUE TITLE
Identify potential user tests

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#20]
Met with @secretrobotron and @LauraReynal on Thursday and drafted a few potential areas for user research. Rough notes:
1. test consumer experience on a few awesome tile projects made by mofo'ers
2. test mobile 
   - nav/zoom/transitions https://github.com/mozilla/webmaker-app/issues/1439
3. design workshops
   - paper test button links (narratives or collaboration) #22 
4. test tinker mode prototype
   - advanced color, learning about hex & css #21 
5. Benchmarking 
   - picCollage on mobile
   - newHive.com on desktop?
   - something more tiles like?

**Comment by secretrobotron** [comment]
From meeting with @thisandagain:
- code editor (on desktop)
- tinkering mode
- tiles on mobile

**Comment by xmatthewx** [comment]
Excellent. Status from where I sit: 
- code editor (on desktop) `needs UX` #17 
- tinkering mode for color  `ready to build`  #25
- tiles on mobile `ready to build` #24 & https://github.com/mozilla/webmaker-app/issues/1439

**Comment by xmatthewx** [comment]
To clarify, when I say `ready`, I mean we know enough about the UX to get started. None of these have finalized UI or artwork ready.

**Comment by xmatthewx** [comment]
Chicago testing in progress.
