### ISSUE TITLE
Design UX for color 'tinker mode'

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#21]
Webmaker will offer users a simple color palette for text, backgrounds, borders etc. Color "tinker mode" will allow users to step beyond the simple set to create custom colors for their projects.

The process of tinkering aims to reward users with the discovery that color has a language we can use to describe, share, copy, and remix color in a digital space.
### Prototype
- basic ui for choosing color from a palette
- button to enter tinker mode :zap: 
- tinker mode has more advanced UI that maps to the underlying code
- recent colors created in tinker mode are added to palette 
### Learning goal
- User understands that color can be expressed in HEX or RGB, making it possible to copy, save, share, and use it anywhere on the web.
- User can read and copy a HEX or RGB value 
- User is aware of the functional relationship between a color, its RGB values, and its expression as HEX.
### Research questions
- Can people utilize the basic UI to set the color on an element?
- Can people utilize the advanced UI to create custom colors?
- Do people discover a relationship between the UI sliders and HEX values?
- Do people realize that there's a language for digital color that enables us to describe, share, copy, and remix it?

![screenshot 2015-03-24 12 20 04](https://cloud.githubusercontent.com/assets/53411/6806608/1dd1b4c4-d220-11e4-8c1e-5c9d305673a4.png)

cc @secretrobotron @LauraReynal

**Comment by flukeout** [comment]
Couple of options here and thoughts:
- RGB sliders suck as a main mode of picking a color, so we should keep a visual one still
- Added indication of relative weights of RGB as you move the UI around
- Format switches from HEX to RGBA and back depending on Alpha value

![image](https://cloud.githubusercontent.com/assets/25212/6813523/20962560-d233-11e4-8f3c-36a9cdba7a25.png)

**Comment by secretrobotron** [comment]
Might be worth testing how users respond to predefined colour palettes (maybe even something autogenerated, like http://app.coolors.co/443742-846c5b-cea07e-edd9a3-e2e8c0).

**Comment by flukeout** [comment]
@secretrobotron I really like this little UI for seeing the effects of your slider movements here...

![image](https://cloud.githubusercontent.com/assets/25212/6813658/7d2668d4-d234-11e4-89fa-7b9c513cfee2.png)

But.. good luck choosing the color you actually want.

The view I posted is the 'tinker' mode, so someone already would have moved past using one of the colors we would have suggested in the previous step.

I'm a little torn between exposing color mode concepts, and allowing you to choose a color easily.

HSL is a nice model for teaching color concepts, but isn't great because it's not a popular web standard.

I do think we could offer some pallette options in the initial color picking phase though.

**Comment by flukeout** [comment]
Hybrid that exposes RGBA sliders alongside a visual colorpicker.
Might be a bit too much stuff crammed into one view though.

![image](https://cloud.githubusercontent.com/assets/25212/6813794/d0f0b018-d235-11e4-97f3-00b657c6fab7.png)

**Comment by secretrobotron** [comment]
> I'm a little torn between exposing color mode concepts, and allowing you to choose a color easily.

If you need to make a decision between one or the other eventually, this could be an opportunity to test both (or all).

**Comment by flukeout** [comment]
Swipe through a bunch of different modes of editing a color, format updates in the line above the UI as you use different ones:

![image](https://cloud.githubusercontent.com/assets/25212/6814514/72195a8e-d23c-11e4-8f6b-5e452872e147.png)

**Comment by flukeout** [comment]
Here's an option that combines a visual colorpicker with RGB sliders. While the sliders suck, they're a cool way to see the effects of modifying one of the values in isolation, and feel like a good way to "tinker".

![image](https://cloud.githubusercontent.com/assets/25212/6829272/c50285ca-d2cf-11e4-9fea-46b6653b26b6.png)

**Comment by xmatthewx** [comment]
Nice mix of options @flukeout 

I agree that RGB sliders are a terrible way to find the color you want. They're also the quickest way to intuit HEX, the most universal language for color on the web. You've stepped toward finding the balance.

> If you need to make a decision between one or the other eventually, this could be an opportunity to test both (or all).

+1 - a quick lo-fi working prototype would help make the case. Since we will likely only launch with tinker mode for color and button links, we can invest a little more time getting it right. 

Let's drop the (?) and the </> so we can focus on the key interaction.

**Comment by flukeout** [comment]
Latest version - https://redpen.io/jb1a5518c142f7e3e4

![image](https://cloud.githubusercontent.com/assets/25212/6836629/25b57450-d301-11e4-8920-6ce2d2d88ee4.png)

**Comment by xmatthewx** [comment]
Excellent work @flukeout. Closing this and opening a fresh ticket for the build.
