### ISSUE TITLE
HTML error on Line 5, Column 45

### ISSUE THREAD

**Issue by satdav** [mozilla/webmaker-desktop#218]
Element meta is missing one or more of the following attributes: http-equiv, itemprop, name, property.
    <meta content="text/html; charset=utf-8">

was using http://achecker.ca/checker/index.php#output_div

**Comment by xmatthewx** [comment]
Thanks @satdav. Let's file issues at https://github.com/mozilla/webmaker-core/issues/ so that everyone sees them.
