### ISSUE TITLE
Make prototype to test button link 'tinker mode'

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#22]
Webmaker will offer people the ability to link from a button placed on their tile to another tile with a simple, visual UI. 

Button "tinker mode" will allow users to link to URLs or tiles by other users to expand the range of their creations.
### Prototype ( paper? ) *****\* WIP ********
- Basic UI for adding and styling a button
- UI for visually setting link destination
- :zap: Button to enter tinker mode
- Tinker mode with option to link to
  - another user's project
  - a URL (type, paste, or select a bookmark)
- Play experience for transition between tiles and out of project

*\* DRAFT **
### Learning goal
- User understands that links use URLs to connect content across the web 
- User understands that a URL is an address that describes where you are or where something exists
- User becomes aware that URLs have a readable structure

*\* DRAFT **
### Research questions
- Can users easily link tiles within their project?
- Can users easily link to another user's tile?
- Can users link to an external URL?
- Do users understand which links are useful for different scenarios?
- Do button links prompt ideas for projects? (non-linear narratives, games)
### Another Question
- Adjacent tiles are automatically linked. Separated a tile becomes an island, making links necessary AND more flexible/interesting. The interface doesn't currently make this obvious. _Maybe we can test a few ideas of how we could do this better?_

cc @secretrobotron @LauraReynal

**Comment by lauradereynal** [comment]
\o/
Thanks @xmatthewx for working on this
Will follow up shortly with a draft for a design workshop

**Comment by flukeout** [comment]
UX first pass - https://redpen.io/mo58e85f30c2f59394

**Comment by thisandagain** [comment]
Awesome. Left one comment for you in the redpen re: learning objectives for URLs.

**Comment by xmatthewx** [comment]
UX for implementation tracked in https://github.com/mozilla/webmaker-app/issues/1524
