### ISSUE TITLE
Switch from html5 routing to GET routing

### ISSUE THREAD

**Issue by errietta** [mozilla/webmaker-desktop#220]
Instead of having "#/project/1/user1" we can have "?project=1&user=1" in our client side code. This will make it possible to process get requests server side as well as client side without having really ugly urls like "/?project=1&user=1#/project/1/user/1"

**Comment by xmatthewx** [comment]
@errietta - I refiled this in the -core repo to keep the discussion visible to everyone. https://github.com/mozilla/webmaker-core/issues/602
