### ISSUE TITLE
Use keyboard arrow keys to navigate in desktop

### ISSUE THREAD

**Issue by errietta** [mozilla/webmaker-desktop#221]
you should be able to navigate with the arrow keys in your keyboard as well as the image arrows

**Comment by secretrobotron** [comment]
:+1:

**Comment by secretrobotron** [comment]
cc @xmatthewx

**Comment by xmatthewx** [comment]
Agreed!! Tracking in the -core repo so that the topic stays visible to everyone. https://github.com/mozilla/webmaker-core/issues/590
