### ISSUE TITLE
Share prior prototypes

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#24]
@flukeout built some excellent prototypes such as [desk8](http://flukeout.com/examples/desk8/). As far as I know, they aren't shared anywhere, though I might be mistaken. 

Let's make them more accessible 
- [ ] link to the best prototypes below
- [ ] post useful code somewhere
- [ ] link to 'best of' usertest results below

This can all wait until next week.

**Comment by thisandagain** [comment]
I think "works in Firefox" needs to be added to the requirements before these can be shared broadly.

**Comment by xmatthewx** [comment]
To clarify, this is a request to circulate things (not broadcast), so that the growing circle on this project can access essential bits without a ping.

**Comment by thisandagain** [comment]
Got it! :+1:

**Comment by xmatthewx** [comment]
sort of accomplished in http://bit.ly/webmaker-build
