### ISSUE TITLE
Build prototype of color 'tinker mode'

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#25]
Webmaker will offer users a simple color palette for text, backgrounds, borders etc. Color "tinker mode" will allow users to step beyond the simple set to create custom colors for their projects.

The process of tinkering aims to reward users with the discovery that color has a language we can use to describe, share, copy, and remix color in a digital space.
### Prototype
- basic ui for choosing color from a palette
- button to enter tinker mode :zap: 
- tinker mode has more advanced UI that maps to the underlying code
- recent colors created in tinker mode are added to palette 
### Learning goal
- User understands that color can be expressed in HEX or RGB, making it possible to copy, save, share, and use it anywhere on the web.
- User can read and copy a HEX or RGB value 
- User is aware of the functional relationship between a color, its RGB values, and its expression as HEX.
### Research questions
- Can people utilize the basic UI to set the color on an element?
- Can people utilize the advanced UI to create custom colors?
- Do people discover a relationship between the UI sliders and HEX values?
- Do people realize that there's a language for digital color that enables us to describe, share, copy, and remix it?
  ---

Latest UX by @flukeout 
https://redpen.io/jb1a5518c142f7e3e4

![image](https://cloud.githubusercontent.com/assets/25212/6836629/25b57450-d301-11e4-8920-6ce2d2d88ee4.png)

cc @secretrobotron @LauraReynal

**Comment by xmatthewx** [comment]
I built a quick prototype to look at highlighting the relationship between sliders and HEX, and the transition from HEX to RGBA.  

updated link: http://jsbin.com/yeheru/

cc @gvn

**Comment by davidascher** [comment]
I guess I don't understand why people still use hex coding for colors in
2015.  Just because we used to doesn't make it a good practice.

From a pedagogical and understandability point of view, it feels
unnecessarily opaque and hard for hard-sake.

Teaching hex can be a way advanced feature if/when actually needed.

**Comment by xmatthewx** [comment]
Agreed.

We'd like to test a few different models for selecting and learning about color. We started with hex because of its ubiquity, to hopefully enable people to grab and reuse colors beyond our platform. 

Most of us prefer HSL to HEX and RGB. Unfortunately hex dominates. Maybe because it's efficient, maybe because of bad inertia.

We'll test these in Chicago to iterate toward the best approach.

**Comment by gvn** [comment]
FWIW: http://caniuse.com/#search=rgb

IMO: RGB is easier to understand than HSL (and more used in CSS by far). Hex is definitely a legacy artifact.

**Comment by xmatthewx** [comment]
mobile-first prototype built http://jsbin.com/yeheru/
