### ISSUE TITLE
Define platform taxonomy

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#26]
It's difficult to talk about the platform and what it makes without using the word **Tiles**. The word is not very exiting and won't resonate with many people who haven't seen the platform. 

Should we avoid, reconcile, or accept this word? Should we start calling them **Pages** before we can't undo the term?

@KevZawacki @HPaulJohnson @thisandagain

**Comment by thisandagain** [comment]
Great question. I think we might want to broaden this to be the full taxonomy. LOTS of different options ... we should pick an approach quickly. Couple iterations showing the structure:

```
[Container] > [Plural] > [Singular] > [Detail]
Project > Pages > Page > Element > Attribute (My favorite)
Project > Tiles > Tile > Component > Attribute
Site > Pages > Page > Block > Setting
Project > Scene > Page > Brick > Detail
```

**Comment by HPaulJohnson** [comment]
Much of what's worked in our testing to-date is around "webpages" or "apps." That said, we haven't tested "tiles," "projects," etc. 

If I had to go with just what's been tested I lean toward site > pages > something. (even so, gut feeling is that "project" is more interesting than "site")

"Apps" is obviously missing and that was a big part of what you "made" with the Beta version. That was central to the value proposition. Curious as to whether it is too much of a stretch to call what users will make "apps" if that's what's proved compelling?

**Comment by thisandagain** [comment]
"Apps" vs. "Sites" is a pretty central question for me that I'd like to resolve. I've been leaning away from using "Apps" as it feels strange when applied to the desktop environment. I also feel like using a more standard "Site" > "Page" paradigm focuses our language on something that feels "webby" and more on-brand. 100% open for discussion.

**Comment by xmatthewx** [comment]
Our favorites align: `Project > Pages > Page > Element > Attribute`

Do we rename aerial view `Project map` or `Project view`? "Map" preserves the visual metaphor and aligns well with site map.

"Apps" - I could see exporting an exceptional project as a standalone App. I don't see that as the primary form.

**Comment by xmatthewx** [comment]
Discussed with the group. Everyone agreed on:

`User/Maker > Project > Map > Pages > Page > Element > Attribute`

cc: @Pomax

**Comment by thisandagain** [comment]
:+1: 
Work for you @HPaulJohnson ?

**Comment by Pomax** [comment]
I think the "Pages > Page > Element > Attribute" taxonomy maps virtually 1:1 with the extant ontologies for the web today, so those have my vote. Calling the higher level views "projects" for a "cohesive collection the user works on", and the aerial view "map" (given its visualisation) seems, to me, intuitive.

I'd also like to posit some term for the user's portfolio of all projects. "gallery" is not an accurate term there, more a secondary term, with the same possibly being true for the map view:

```
conceptual: User > Portfolio > Project > Pages > Page > Element > Attribute
                       v          v
explorables:        Gallery      Map
```

Steps in the conceptual taxonomy are "consists of", steps from conceptual to explorable are "presented as"

**Comment by thisandagain** [comment]
:+1: I was feeling a little uncomfortable with "Map" in the taxonomy above and this expresses why really clearly. I like how you have "Gallery" and "Map" positioned as explorable collections here. This is starting to feel pretty solid.

**Comment by xmatthewx** [comment]
:+1:

**Comment by gvn** [comment]
`map` is an array method, which makes me want to pick something more unique. :dancers: 

Also, Element and Attribute are already used in HTML, so that may cause some confusion since I think Elements are more like custom components?

**Comment by xmatthewx** [comment]
Instead of `map`, we could go with `pagemap`, `projectmap`, `mapview`.

It's true that future elements might be more component like. I'd still rather use the word element for anything user facing.

**Comment by thisandagain** [comment]
Yup. I'm good with just saying "project" or "project map".

I like the `Page > Element > Attribute` naming as it roughly maps to what users will experience when they start to dig in deeper with the technology (inspect in dev tools, etc).

**Comment by xmatthewx** [comment]
I've been using to the word 'Play' to describe what you do with a project, rather than 'Open' or 'View'. It sounds more immersive and fun, but might imply a game or video and confuse people.

Might be worth testing. 
cc @HPaulJohnson @LauraReynal

**Comment by Pomax** [comment]
I'm not sure "map" is ambiguous, it has a fairly clear meaning outside of HTML already; people who don't write JavaScript won't get confused, and I would expect people who do use JavaScript to understand that, since it's not written as `thing.map()`, it's not the JS function call. That said, "overview" would work just as well. 

The element/attributes names, however, I think are the only correct terms here. Even if you think in terms of HTML, that's the exact thing we're letting people put on their pages: they are adding markup elements, and editing the attributes that control the behaviour of those elements

**Comment by xmatthewx** [comment]
Done. Work continues in https://github.com/mozilla/api.webmaker.org/issues/

**Comment by Pomax** [comment]
wait, so what taxonomy did we settle on? (do we have a link to it?)

**Comment by xmatthewx** [comment]
Documented in the [build deck](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.gacde6376b_0_109) and getting clarified in the [api issues](https://github.com/mozilla/api.webmaker.org/issues/5#issuecomment-94594514).

It seemed settled in our last realtime discussion. Glad to reopen the topic if there's interest.

**Comment by Pomax** [comment]
Only reopened it to make sure those links got added so the issue ends with a tangible conclusion. I'll reclose it now that we have that final bit, thanks!
