### ISSUE TITLE
Implement desktop marketing page for Android Beta

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-desktop#30]
Implementation notes available in https://github.com/mozilla/webmaker-app/issues/1457

Sketch File:
https://www.dropbox.com/s/cwoegt612voxydk/App%20Landing%20Page.sketch?dl=0

**Comment by thisandagain** [comment]
Current progress available here: https://pure-crag-8461.herokuapp.com/
/cc @vazquez @xmatthewx @k88hudson

**Comment by thisandagain** [comment]
Production instance now available at http://beta.webmaker.org

**Comment by thisandagain** [comment]
Ready to go: https://beta.webmaker.org

/cc @secretrobotron @xmatthewx @hpauljohnson

**Comment by HPaulJohnson** [comment]
Great! Can we redirect webmaker.org/app traffic here too? Or, should I submit a separate issue to make that happen?

**Comment by thisandagain** [comment]
@HPaulJohnson Read my mind ... I'm on the case.

**Comment by xmatthewx** [comment]
applause :clap:

**Comment by thisandagain** [comment]
@HPaulJohnson https://webmaker.org/app is now redirecting to the new beta.w.o site.
