### ISSUE TITLE
Add responsive styles

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-desktop#34]

**Comment by thisandagain** [comment]
We don't have a spec, so the goal here is to just try to execute something simple that removes the following as the `media-width` goes below the current minimum width: 966px.
- Removes the `hero` image
- Removes the social buttons
- Stacks the quote and feature divs

/cc @vazquez

**Comment by vazquez** [comment]
@thisandagain I have all that already in an updated design I did earlier
today. Perhaps the Sketch file didn't update correctly in Dropbox. Let me
get back to you with an updated URL.

On Thursday, May 7, 2015, Andrew Sliwinski notifications@github.com wrote:

> We don't have a spec, so the goal here is to just try to execute something
> quickly that removes the following as the media-width goes below the
> current minimum width: 966px.
> - Removes the hero image
> - Removes the social buttons
> - Stacks the quote and feature divs
> 
> /cc @vazquez https://github.com/vazquez
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/webmaker-desktop/issues/34#issuecomment-100092106
> .

## 

Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez http://twitter.com/iamrvazquez
IRC: ricardo

**Comment by vazquez** [comment]
@thisandagain :dancers: https://www.dropbox.com/s/cwoegt612voxydk/App%20Landing%20Page.sketch?dl=0

**Comment by xmatthewx** [comment]
![landing-mobile-ui](https://cloud.githubusercontent.com/assets/53411/7540807/611166fe-f57e-11e4-9bb6-27bdafa20f1a.png)

**Comment by xmatthewx** [comment]
Closed by #64
