### ISSUE TITLE
Implement error reporting UI for signup form

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-desktop#55]
From #33
Blocks #30

Need two error states: checkbox not checked, and invalid email.

Back-end should already be in order. Just need UI.

**Comment by secretrobotron** [comment]
cc @thisandagain 

Tooltip? Giant red arrow? What do you think?

**Comment by vazquez** [comment]
What do you think? Copy can change.

![screenshot 2015-05-12 11 46 18](https://cloud.githubusercontent.com/assets/1119821/7591619/e5d6552c-f89c-11e4-9589-207e05adf61c.png)
![screenshot 2015-05-12 11 48 54](https://cloud.githubusercontent.com/assets/1119821/7591620/e5d76228-f89c-11e4-93a7-7ced461010cf.png)

**Comment by thisandagain** [comment]
Thanks @vazquez. :+1: 

Work for you @secretrobotron ?

**Comment by vazquez** [comment]
Use case: User clicks on `GO` before entering email or checking the checkbox.
Result: Only the `invalid email` notification shows up.
Purpose : To not overwhelm the user by showing 2 messages at the same time.

**Comment by secretrobotron** [comment]
Totes!

**Comment by xmatthewx** [comment]
:+1: you can use the left aligned arrow for both notices to simplify.
