### ISSUE TITLE
UI for Browser-based player

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#57]
A simple project player for visitors on non-android devices.

Requirements:
- Webmaker logo
- `Get the App` (for desktop users with an Android)
- Responsive desktop/mobile
- Fwd Android users to play store

**Comment by flukeout** [comment]
**Desktop Player**

![image](https://cloud.githubusercontent.com/assets/25212/7621770/2c8c01b0-f97e-11e4-8908-169bae4a0e5f.png)

**Comment by flukeout** [comment]
Need to add some kind of "made with Webmaker" messaging and CTA

**Comment by flukeout** [comment]
**Mobile Player**
If viewed on an Android device, we will redirect users to the Play store.

![image](https://cloud.githubusercontent.com/assets/25212/7621819/b84c952a-f97e-11e4-9793-3d3b0f96e8dc.png)

**Comment by flukeout** [comment]
@xmatthewx - This is the final UX with the adjustments made from our crit call.

**Comment by xmatthewx** [comment]
:+1:

@thisandagain - Let's estimate the engineering hours and then see where we stand in the next couple weeks. 

Reference diagram by @flukeout of how users arrive here: https://github.com/mozilla/webmaker-android/issues/1616#issuecomment-101424066

**Comment by thisandagain** [comment]
Excellent. Sounds good. @xmatthewx added to agenda for Monday PM meeting.

**Comment by xmatthewx** [comment]
@vazquez - this is a good place to start UI work for desktop. Smells like today's episode of an _hour of design_. Err toward simplicity.

**Comment by secretrobotron** [comment]
FTR, right now, visiting a share link in desktop chrome does nothing. It just stops loading right away.

**Comment by vazquez** [comment]
### UI Progress

Some notes:
- I am maintaining the same aspect ratio in the pages as what we have in mobile.
- The view looks simple, but it will evolve in time (addition of share, discovery, etc)

##### Desktop Map Play View

![desktop map](https://cloud.githubusercontent.com/assets/1119821/8169708/47408a20-1379-11e5-8092-464a7b50f120.png)  

---

##### Desktop Page Play View

![desktop page](https://cloud.githubusercontent.com/assets/1119821/8169709/474a95a6-1379-11e5-9dbc-4901dad841f5.png)

cc @xmatthewx @thisandagain @flukeout @cassiemc

**Comment by xmatthewx** [comment]
- Simple but does the job. Logo and header look great. 
- Show us hover state for the nav arrows and zoom icons.
- I'm a little nervous about the +/- zoom in the bottom right corner, but that is where google maps places it.

**Comment by vazquez** [comment]
@xmatthewx -
- :+1: on the hover states, coming up!
- You're right on the money with the Google Maps benchmark. We can see how we feel about it, but another possibility would be top right (where the app notice is right now)

**Comment by vazquez** [comment]
#### Hover States
- For the Zoom-In/Zoom-Out buttons, we are dropping the brightness down when the user hovers.
- For the navigation arrows, we are scaling the arrow and making the hovered-on page a bit more opaque.

![desktop map hover](https://cloud.githubusercontent.com/assets/1119821/8184574/1be63f84-140d-11e5-9238-c86efd7f58a0.png)

![screenshot 2015-06-16 09 52 17](https://cloud.githubusercontent.com/assets/1119821/8184613/6386e730-140d-11e5-9159-976a5a68dd3e.png) ![screenshot 2015-06-16 09 51 18](https://cloud.githubusercontent.com/assets/1119821/8184598/46fb4b24-140d-11e5-876a-dae7820c001c.png)

---

![desktop page hover](https://cloud.githubusercontent.com/assets/1119821/8184575/1bfb1fd0-140d-11e5-9bb1-a053d034176d.png)

**Comment by vazquez** [comment]
After pair-designing chatting with @xmatthewx, we found that the slate allowed the google play button to have more visual hierarchy.

![app landing page blue solid copy 5](https://cloud.githubusercontent.com/assets/1119821/8209816/1398c4c0-14dd-11e5-9043-9feabf064ba9.png)

**Comment by xmatthewx** [comment]
@thisandagain R?

(we'll switch label from 'dismiss' to 'no thanks')

**Comment by vazquez** [comment]
![app landing page blue solid copy 5](https://cloud.githubusercontent.com/assets/1119821/8211262/26ee304e-14e4-11e5-8e52-debe8c1f3df1.png)

**Comment by xmatthewx** [comment]
Let's see how this translates to a mobile browser @Vazquez

**Comment by xmatthewx** [comment]
scope:
- users arrive strictly thru shared URLs
- build just a minimal project viewer
  - no sharing from here
  - no discovery 
- support
  - mobile `p1`
  - desktop `p2`

**Comment by xmatthewx** [comment]
ux/ui
- add author name with cc icon link to license
- project view: 
  - correct page margins
  - coherent zoom UI across screensize, touch and click
- page view:
  - page to page nav (update Android)
- define responsive
- define states: hover/transitions/loading/error etc

**Comment by xmatthewx** [comment]
# Project viewer

Notes for consistent build across Android and browser, touch device and desktop. 

![project-viewer](https://cloud.githubusercontent.com/assets/53411/8630069/855c9e9c-272f-11e5-8d75-18e5c85091a2.png)

**Comment by xmatthewx** [comment]
# Page viewer

Notes for consistent build across Android and browser, touch device and desktop. 

![page-viewer](https://cloud.githubusercontent.com/assets/53411/8599829/9b7e4f5e-2630-11e5-84cb-d7f5e21b57f7.png)

**Comment by xmatthewx** [comment]
@gvn - here's a draft meta list of tasks: 
- [x] in-browser wrapper (migrate webmaker-browser to use core)
- [ ] project view
  - tap to open page
  - pan
  - zoom (touch devices only)
- [ ] page view
  - render neighbors
  - page to page nav
  - zoom out to exit
- [ ] get the app cta
  - landscape browsers only
  - dismiss and stay dismissed
- [ ] android changes
  - page size in page view
  - margins between pages
  - page to page nav icons
- [x] refactor page rendering for thumbnail sevice
- [ ] localization

**Comment by secretrobotron** [comment]
Already documented elsewhere, but worth mentioning: localization.

**Comment by xmatthewx** [comment]
True. Also adding refactor of rending for thumbnails.

**Comment by gvn** [comment]
One thing I've noticed so far: pinch zooming is indicated for Browser on Project Viewer, but that's typically not available in a "desktop" situation.

**Comment by xmatthewx** [comment]
Pinch zoom is nice to have on a mobile browser, but not critical to our first release of this.

**Comment by gvn** [comment]
Looks good. A couple things:
1. There may be cases where making the page/tile full width will overflow vertically (depends on the aspect ratio of the device).
2. CTA modal will probably be shown based on viewport width instead of based on device. Not sure we can get reliable client side device detection.

**Comment by xmatthewx** [comment]
Here's a spec to handle aspect ratio on small screens. @flukeout - if this looks good, re-post to #154

![responsive-page-style](https://cloud.githubusercontent.com/assets/53411/8630101/c9add82c-272f-11e5-9842-087bd1053e2b.png)

**Comment by flukeout** [comment]
@xmatthewx To me, it feels better to always attach the "moons" to the edge of the screen, until we have enough real state to turn them into the little floating arrows. That way they seem more a part of the view port rather than the page itself. 

cc @vazquez Thoughts?

**Comment by gvn** [comment]
+1

**Comment by vazquez** [comment]
I like @flukeout's approach as well. It obfuscates the current page less that way.

**Comment by xmatthewx** [comment]
:+1: Attaching moons to edge of screen :+1:

**Comment by xmatthewx** [comment]
This is largely done. File new things as needed.
