### ISSUE TITLE
Get ready for localization

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-desktop#66]
See https://github.com/mozilla/webmaker-android/issues/1599#issuecomment-103712914 for recommendations
- [ ] install a i18n library (Android XML?)
- [ ] provide API (gettext?)
- [ ] add filters to static files
- [ ] add filters to functional code (where necessary)
- [ ] upload json files to Transifex
- [ ] shout-out on Transifex

**Comment by xmatthewx** [comment]
@secretrobotron - is this tracked in -core or -launch?

**Comment by secretrobotron** [comment]
@alicoding and I talked about it today. This should just be linked to https://github.com/mozilla/webmaker-core/issues/148
