### ISSUE TITLE
Build new terms page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#67]
Design UI for secondary pages linked from the footer of the landing page (terms, contact). A simple, responsive template with basic styles. No need to invest more than a couple hours.

**Comment by vazquez** [comment]
### Terms Page

The Privacy page will also share the same simple header.

![terms of service copy](https://cloud.githubusercontent.com/assets/1119821/7941984/e9091dd2-0928-11e5-9ca7-4ae92708c026.png)

**Comment by vazquez** [comment]
### Aspirational Design Elements

I dreamed up the idea of us having a developer.webmaker.org page to help me design layout.

These are some design elements we can use in the future:

![app landing page teal gradient copy 3](https://cloud.githubusercontent.com/assets/1119821/7940968/357d9f8c-0922-11e5-9b9a-7dc1b273e402.png)

**Comment by vazquez** [comment]
### 404 Page

![404](https://cloud.githubusercontent.com/assets/1119821/8008646/762bad8e-0b71-11e5-91bc-49e84c618705.png)

**Comment by xmatthewx** [comment]
Great. I think these work for our barebones site on launch.

**Comment by xmatthewx** [comment]
:+1: ready to implement the new terms page. refilling accordingly.

**Comment by gvn** [comment]
@vazquez Can you link me to either plain text for all that copy or the Sketch file w. the copy?

**Comment by vazquez** [comment]
@gvn - Definitely, here is the Sketch file. https://drive.google.com/a/mozilla.com/file/d/0ByIoeeW0a3R_NmEyZllJX1VkUk0/view?usp=sharing

I took the text from what currently exists on webmaker.org (updated June 15, 2013). @thisandagain, is there a more up-to-date legal copy?

**Comment by thisandagain** [comment]
Yup! Still WIP but here is the file (please use what is here and we can update after legal review):
https://docs.google.com/document/d/1Os_JUdGdfBR48CBGKMUj5NIWXIbu6hIsxo2NhAjk8rU/edit

**Comment by xmatthewx** [comment]
Looks done to me. File new issues for any content updates.
