### ISSUE TITLE
Add deep-link redirect for beta.webmaker.org/projects/:pid

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-desktop#69]
Users who land at a sharing link on Android should be redirected to the app via a deep-link. Technique described here:
https://developer.android.com/training/app-indexing/deep-linking.html

**Comment by secretrobotron** [comment]
Blocks https://github.com/mozilla/webmaker-android/issues/1665

**Comment by thisandagain** [comment]
Is this still a blocker for you @secretrobotron now that you have DB access?

**Comment by secretrobotron** [comment]
It would still be very, very useful to have this ability soon. I can find things in the DB and feature them, but I would still love to be able to send people to a make directly if I want them to see a good example of something.

**Comment by thisandagain** [comment]
:+1:

**Comment by secretrobotron** [comment]
If you're on your phone and receive a share link, it'll boot up the app and show you the project. What will happen on desktop if the player doesn't get done though? Can we detect a desktop browser and say, "use your phone, lol!"?

**Comment by secretrobotron** [comment]
On mobile, could we show the project as we would on desktop? (play mode)
And have a popup that says, "view this in Webmaker!" which guides people to download the app.

**Comment by xmatthewx** [comment]
Agreed. 
- If we `don't` land the player, a redirect to the landing page would be better than a 404. 
- If we `do` land the player, it will include a big button to get the app. (#57)

Platform scenarios mapped here: https://github.com/mozilla/webmaker-android/issues/1616#issuecomment-101424066

**Comment by secretrobotron** [comment]
:+1: How soon do you think we can evaluate which route we'll be able to take?

**Comment by thisandagain** [comment]
Proposal:
- User-agent detect
- If Android:
  - Redirect to deep link `webmaker://play` etc.
- If Other:
  - Show player if landed. If not:
  - Redirect to Google Play store

**Comment by thisandagain** [comment]
FWIW the deep link redirect is already landed:
`https://beta.webmaker.org/users/:user/projects/:project`

**Comment by secretrobotron** [comment]
We should morph this ticket to account for the other cases then?

So, if a user is on a desktop machine, and we don't land the player, they will be shown to the google play store anyway? ( :+1:  ).

**Comment by thisandagain** [comment]
Yeah. I think I'd prefer that over cycling back to the splash page. Gets us one step closer to a conversion.

**Comment by secretrobotron** [comment]
:+1:

**Comment by secretrobotron** [comment]
Filed #91 to follow up on other cases.
