### ISSUE TITLE
Update the 404 page 

### ISSUE THREAD

**Issue by edrushka** [mozilla/webmaker-desktop#70]
Update the 404 to match the webmaker-desktop design.

CC: @cassiemc @thisandagain

**Comment by xmatthewx** [comment]
@vazquez - I remember seeing designs for a 404 page. Can you post those here?

**Comment by mmmavis** [comment]
@xmatthewx is it https://github.com/mozilla/webmaker-browser/issues/67#issuecomment-108021418 ?

**Comment by xmatthewx** [comment]
@mmmavis - yes. But I think we should update this so we can include a helpful link or two to Teach. cc @vazquez

**Comment by xmatthewx** [comment]
Also could include:  Can't find it? “try old.webmaker.org/querystring”

**Comment by mmmavis** [comment]
Note that this page exists already (try visiting https://beta.webmaker.org/#/hello12345) but we can update it.

We should probably consider removing hash from the URL to make pages on the site more accessible. (I'll create a separate ticket for this)

**Comment by xmatthewx** [comment]
It's weird that it has a tagline above the not found error. Let's remove that.

**Comment by mmmavis** [comment]
We figured that weird tagline "Imagine the Possibilities" was introduced (wrongly) by Optimizely which is now fixed. Are there any other changes to UI that we should modify?

**Comment by xmatthewx** [comment]
If we fix the /#/ problem, this is good enough for launch. 

From a comms perspective, we might want a helpful temporary link to Teach and the site archive. Below the button. cc @KevZawacki @hannahkane

<img width="609" alt="screenshot 2015-07-20 15 38 44" src="https://cloud.githubusercontent.com/assets/53411/8785396/72b01882-2ef5-11e5-8146-a5e0957841df.png">

**Comment by hannahkane** [comment]
Not sure what that copy would be for the link to Teach. Maybe, "Or visit the home of the Mozilla Learning Network". @kevzawacki?

**Comment by KevZawacki** [comment]
"Mozilla Learning Networks" isn't a name we've used a lot in external comms. So, how about:

"Or visit teach.mozilla.org"

**Comment by xmatthewx** [comment]
That works. Ready to build it?

<img width="830" alt="screenshot 2015-07-22 09 47 38" src="https://cloud.githubusercontent.com/assets/53411/8826764/c62db9e4-3056-11e5-9ca5-d0af3de0e7c4.png">

**Comment by vazquez** [comment]
@mmmavis Small tweak. Can we use this button style instead?

<img width="503" alt="screenshot 2015-07-22 09 51 13" src="https://cloud.githubusercontent.com/assets/1119821/8826843/3bac6ada-3057-11e5-9521-5a82cf6088bc.png">

Full Sketch File available here: https://drive.google.com/a/mozilla.com/file/d/0ByIoeeW0a3R_cGNIRFhDSVpocEU/view?usp=sharing

I can do the PR review for this page :)

**Comment by mmmavis** [comment]
yup yup will get to this today :hamster:

**Comment by mmmavis** [comment]
@vazquez how does the "GET STARTED" button on https://beta.webmaker.org/#/ look to you? If there's anything that needs to be tweaked I can tweak them all at once (assuming the 2 buttons share the same `class`)

**Comment by vazquez** [comment]
Sorry for the delay @mmmavis. The only thing is to add line-height :)

`line-height: 15px`

**Comment by vazquez** [comment]
Right now it seems like most of the styling lives on the `#splash .btn` class. We can refactor the CSS a bit and move the styling up a level to just the `.btn` class so that we can reuse it. That, `#splash .btn` can just modify the color properties of the button.

**Comment by mmmavis** [comment]
@vazquez 

I don't seem to find `#splash .btn` class anywhere.  Did you mean [`.btn in .promoMixin`](https://github.com/mozilla/webmaker-browser/blob/04ea32c9846c3fa77d47ab6c466e9b4a94c5cc13/src/components/promo/promo.less#L23-L36)?

**Comment by vazquez** [comment]
Yes! that's the one! Sorry I was looking at the output CSS.
