### ISSUE TITLE
Post promo guidelines for Webmaker.org to build.webmaker.org

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#79]
Webmaker.org includes a spot for promotion of partners and activities. We have some draft guidelines (https://github.com/mozilla/webmaker-desktop/issues/68#issuecomment-108458057) that should be finalized and posted to build.webmaker.org for posterity.

**Comment by xmatthewx** [comment]
tiles guidelines as reference: https://app.box.com/s/ykpzhcz0drmyd42q2kluzf7a75j7yxo6 via @sabrinang via Aaron Thornburgh.

**Comment by vazquez** [comment]
This guideline can guide the discussion at Whistler.

![promo 2](https://cloud.githubusercontent.com/assets/1119821/8193881/d8405376-1445-11e5-9039-c3b8d3776536.png)

cc @xmatthewx @cassiemc

**Comment by vazquez** [comment]
@cassiemc and @lovegushwa I would love your eye to see if the colour palette works. 

The ZIP is here: https://dl.dropboxusercontent.com/u/43783651/Mozilla/Android/Colours.zip

## ![c1](https://cloud.githubusercontent.com/assets/1119821/8193798/519292ee-1445-11e5-8987-7f8842a801c3.png)

## ![c2](https://cloud.githubusercontent.com/assets/1119821/8193799/51948c0c-1445-11e5-9617-b5e022578a5e.png)

## ![c3](https://cloud.githubusercontent.com/assets/1119821/8193800/5194ec4c-1445-11e5-81f0-f400733f2787.png)

## ![c4](https://cloud.githubusercontent.com/assets/1119821/8193803/5198c588-1445-11e5-8695-196c037014d1.png)

## ![c5](https://cloud.githubusercontent.com/assets/1119821/8193801/51964a6a-1445-11e5-9fea-9d53c8045073.png)

## ![c6](https://cloud.githubusercontent.com/assets/1119821/8193802/5197eab4-1445-11e5-8777-c21eb3607fcc.png)

## ![c7](https://cloud.githubusercontent.com/assets/1119821/8193805/519ef9da-1445-11e5-8bcf-1c3ec629234e.png)

![c8](https://cloud.githubusercontent.com/assets/1119821/8193804/519baa82-1445-11e5-9089-eeb913f47f76.png)

**Comment by xmatthewx** [comment]
Thanks for all the mockups. I like the candy colors, particularly green, yellow, and orange. The first really dark one doesn't feel right to me. We should claim the gradient as our own. I would remove those two, but I'm curious what @cassiemc and @lovegushwa think.

**Comment by vazquez** [comment]
I hear you on the dark colour, the more I see it the darker it gets.

Everyone, what about this colour?

![c1](https://cloud.githubusercontent.com/assets/1119821/8210389/baaaf876-14df-11e5-814b-c5ceadb3ab2e.png)

**Comment by vazquez** [comment]
The Aruba Teal we can remove as it can be too similar to the colours up top.

**Comment by xmatthewx** [comment]
:+1:

**Comment by cassiemc** [comment]
@vazquez @xmatthewx I like the first dark one for mirroring the colors in the wings, but also really like the purple, green and yellow and blue. The grey and orange feel a little disjointed. 

Have you thought about adding very subtle gradients in the bottom section? I mentioned in a bug for @sabrinang that it feels like there's a slight, uncomfortable tension between the top gradient and the bottom pattern.

**Comment by cassiemc** [comment]
Maybe the gradient is already there, seems more obvious in some versions.

**Comment by vazquez** [comment]
We talked about the guideline during design critique. This is a revised version:

![promo 2 copy](https://cloud.githubusercontent.com/assets/1119821/8234436/ef93135a-15a9-11e5-9ad6-b1fa6c2beaad.png)

**Comment by xmatthewx** [comment]
Excellent. Beautifully unambiguous.
