### ISSUE TITLE
Benchmark solutions

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#8]
Got benchmarks? Please add 'em to this [slide deck](https://docs.google.com/a/mozilla.com/presentation/d/19CWmjTx-7_nUDgB9NUkVxOQdON-vIVYEDJbw-SWr2mQ/edit?usp=sharing).

We're looking for actionable examples that answer specific design questions we face (not general references). For example, what's a keen way to navigate tiles, provide code hints, edit element attribute?    

cc @iamjessklein @cassiemc @flukeout @sabrinang @vazquez

**Comment by cassiemc** [comment]
Don't have time currently to add to the deck, but here's my list from email (many re. big picture look & feel / might be helpful in UI research):
- https://www.mapbox.com/design/
- windows tiles
- flipboard
- material design - http://materialdesignblog.com/material-design-tiles-animation/?utm_source=twitter&utm_medium=twitter
- http://nylllon.com/
- pinterest
- http://butdoesitfloat.com

**Comment by xmatthewx** [comment]
@sabrinang - mind adding a few benchmarks to the [slide deck](https://docs.google.com/a/mozilla.com/presentation/d/19CWmjTx-7_nUDgB9NUkVxOQdON-vIVYEDJbw-SWr2mQ/edit?usp=sharing) specifically around UI? 

|  | mobile | desktop |
| --: | :-: | :-: |
| editor | :star2: | :boom: |
| gallery | :rocket: | :poodle: |

**Comment by xmatthewx** [comment]
Covered fairly well in [the deck](https://docs.google.com/a/mozilla.com/presentation/d/19CWmjTx-7_nUDgB9NUkVxOQdON-vIVYEDJbw-SWr2mQ/edit?usp=sharing), though something we can revisit and improve on later.
