### ISSUE TITLE
Document share experience

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#80]
As mentioned by @benrito, sharing is core to Webmaker's value. Our intro deck and promo video would benefit from showing more of the experience. 

@vazquez is mocking up Android's share card with logos. That's easy to add. We can also either:
- mock up a project shared on facebook
- try it and screenshot it for realz in the very near future

@thisandagain - should our desktop player include an og meta tag for the thumbnail?

**Comment by thisandagain** [comment]
Yup! Mind filing a follow-up ticket for OG tags? Now that we have copy for Google Play it makes getting that done much easier.

**Comment by xmatthewx** [comment]
OG tags => #82

**Comment by xmatthewx** [comment]
@vazquez added two new views of the share experience to the [intro deck](https://docs.google.com/presentation/d/1fdb6gJ1XMY7UJdh9Ac5r8_Ic0PAnimEKVXkj9w7wD6w/edit#slide=id.gb30f58fab_1_20).

**Comment by benrito** [comment]
gracias

**Comment by xmatthewx** [comment]
@vazquez - let's add a second screen to the [remix slide](https://docs.google.com/presentation/d/1fdb6gJ1XMY7UJdh9Ac5r8_Ic0PAnimEKVXkj9w7wD6w/edit#slide=id.g98178a36f_0_145). Second view is a copy of the first...
- change to title to "Remix of Wa..."
- hide more actions menu
- make an obvious change to one of the pages

**Comment by vazquez** [comment]
Done!
