### ISSUE TITLE
Whistler - Webmaker on Desktop

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#81]
During our time in Whistler, there are a few things we can jumpstart for Webmaker on desktop: Architecture considerations; UI adjustments for clicks and wide screens; Code for users. 

**Code on desktop** - here's a sketch of how we can approach it:  
- **Part 1** - Can code enhance Webmaker’s new platform for content discovery, making, and sharing? How? Why? What’s possible, probable, desirable? (1 hour)
- **Part 2** - Explore 2-3 concepts based on the answers in part 1. (2-3 hours) 
- **Part 3** - Prototype an interesting slice of the concepts in part 2 to demonstrate a key user experience. (half day??)

Beyond the team, it would be great to get input from MDN, Teach, MoCo at-large during any part of this.

cc @secretrobotron @LauraReynal @thisandagain @flukeout

**Comment by xmatthewx** [comment]
Some notes: https://docs.google.com/document/d/1ZH8mpDj_uZKPfDn2W4sVW0q_rGwLAzyPEWtb0pclMig/edit?usp=sharing

**Comment by xmatthewx** [comment]
@OpenMatt - discuss if/how this fits into our plans with @thisandagain.

**Comment by xmatthewx** [comment]
There are limited slots on the schedule when we could have a cross-team meeting to talk about how Webmaker might offer code to users. Details aside, there are big differences on the paths we might take. It'd be great to tackle this in person. Friday during the lunch hour seems a bit too late for generating good ideas.

**Comment by OpenMatt** [comment]
@thisandagain : what do you think? Is Friday too late for this? We could also extend the Webmaker for Desktop kick off to start earlier in the day on Friday, running from 9am to 1pm, for example.

**Comment by thisandagain** [comment]
This is likely bigger than we have time in the schedule for. That said, @OpenMatt I'd love to steal that morning slot as well if we can get it! @xmatthewx let's get this down to size given the schedule tomorrow after stand-up ... I still think we can get through most of this. :smile:
