### ISSUE TITLE
demo account

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#83]
We need an easy demo account for Webmaker.  Do we have an address like demo@w..m.....org ?? If not, is this a service-now or @jbuck request?

cc @secretrobotron @LauraReynal @amirad

**Comment by amirad** [comment]
will help@webmaker.org do? There is also info@webmaker.org

**Comment by secretrobotron** [comment]
Nice. Who reads info@ now? Kevin?

**Comment by xmatthewx** [comment]
Those work, though demo@ might have less security concerns if a bunch of us are using it.

**Comment by secretrobotron** [comment]
:+1: good call. I think this is a @jbuck task.

**Comment by jbuck** [comment]
First you'll need to create a group mailing list. Head to https://groups.google.com/a/mozillafoundation.org/forum/?hl=en#!creategroup to create one, and invite everyone who should be sharing it. Next, file a bug at https://github.com/MozillaFoundation/mofo-devops/issues/new telling me what webmaker.org email alias you want (demo@webmaker.org I guess?), and the google groups email you created.

**Comment by secretrobotron** [comment]
Looks like someone's on this task. demo@mozillafoundation.org is taken.

@xmatthewx did you try already? If not, I'll use something else and grab the webmaker.org alias.

**Comment by xmatthewx** [comment]
I set that up today and filed: https://github.com/MozillaFoundation/mofo-devops/issues/98. Though, I see there's some confusion there now.

**Comment by xmatthewx** [comment]
@secretrobotron I created a user called `demo` utilizing demo@mofo. Let's reassign a few feature projects to this user: Button Links!, Maker People, and Six Word Stories.

**Comment by secretrobotron** [comment]
@xmatthewx I'd actually like to attach those to real people so the platform looks a bit more personal and used. Maybe I'll assign those to dev team members. What do you think?

**Comment by xmatthewx** [comment]
Sure, but let's assign Maker People to demo b/c I want a bunch of us to try it in prep for Maker Prom. We could give our friend "demo" a better name if you want. or a weird name like `demo-cat` :smile_cat:

**Comment by xmatthewx** [comment]
Calling this done. If anyone needs access to the demo account, ping me.
