### ISSUE TITLE
Short share URLs

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#84]
@secretrobotron mentioned this. I filed it under desktop alpha. Bump it up if you think it's important to have that sooner.

**Comment by secretrobotron** [comment]
Did I mention this? Can you explain a bit for my poor memory? :S

**Comment by xmatthewx** [comment]
Maybe I misunderstood.  On IRC today you talked about Urls for sharing on Facebook and Twitter. Figured you meant short links.

**Comment by secretrobotron** [comment]
I meant more the OG stuff (which I found other issues for). But, this works :).

**Comment by xmatthewx** [comment]
Eh. Closing. Can revisit later if feedback points this way.
