### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#88]
Update footer links
- Legal
- Privacy
- Donate[1]
- Contact
- Twitter

[1] https://sendto.mozilla.org/page/contribute/join-mozilla?source=join_link

@vazquez - can you add a quick comp with just the footer and five links above? Thanks!

**Comment by vazquez** [comment]
@xmatthewx - Can I code it instead? Or would you like to see how it looks first?

**Comment by xmatthewx** [comment]
Code it up.
