### ISSUE TITLE
Target screens (desktop/tablet) 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#9]
On desktop, the product plan originally assumed 1024 × 768 to cover low end laptops/desktops and match iPad proportions (4:3). Should we stick with that?

**I propose we shift to 1280 x 800 (8:5)** as a midpoint between squarish and HD 1366 × 768 (16:9), common for new laptops... so we don't overuse the vertical space. 8:5 also matches Nexus and Galaxy Tab proportions. 

![screen-proportions](https://cloud.githubusercontent.com/assets/53411/6621841/49c7f4e6-c8af-11e4-9c6b-73329bf1ea3a.png)

cc @thisandagain @simonwex @cassiemc @davidascher 

on mobile - https://github.com/mozilla/webmaker-app/issues/1429

**Comment by thisandagain** [comment]
I think I’d rather stick with 1024 x 768 (4:3) as that gives us a solid constraint for not only iPads but also many Chromebooks. In either case, we'll need to design the UI to adapt, so either 4:3 or 8:5 is fine as long as we have a plan for how those elements scale by the end of the next heartbeat (UI).

**Comment by xmatthewx** [comment]
@vazquez @flukeout @sabrinang @iamjessklein - stay mindful of how screen proportions will impact UI. Tool spaces can lose 25% of their height between 4:3 and 16:9 screens. 

For implementation, note what bits should scale, remain fixed, or scroll on your mockups so we can maintain nice margins and alignment while we avoid an _everything is elastic_ approach to responsive.

**Comment by flukeout** [comment]
Some tablet screens are here: http://invis.io/HE2FK9JTP
These are using a 4:3 ratio - will mock a screen with a 16:9 ratio as well.

Most of the screen types are here, although we haven't fleshed out the prototype to the same extent as the mobile version.

**Comment by flukeout** [comment]
@xmatthewx @thisandagain The 8:5 and 16:9 ratios you listed above both have the same or more vertical pixels than the 4:3 we've been using. This means we're not giving up any vertical space, are we? We're just gaining horizontal space? I guess we should deal with physical screen sizes instead of pixel dimensions and then we can measure the actual physical size of our UI elements instead of pixels.

**Comment by thisandagain** [comment]
Yup! That's right @flukeout ...if we stick with the 44 points square (from Apple HIG) target size for interactive UI elements we should be ok. I believe that works out to about 1.55cm square. FWIW ... Microsoft's HIG suggests that down to 7mm square is ok if we need to push it in a few places.

**Comment by thisandagain** [comment]
Bookmarks dump! 
:truck: :books: :books:

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/LayoutandAppearance.html
http://maya.com/blog/on-touch-target-size
http://www.uxmatters.com/mt/archives/2013/03/common-misconceptions-about-touch.php
http://www.lukew.com/ff/entry.asp?1085

**Comment by flukeout** [comment]
![image](https://cloud.githubusercontent.com/assets/25212/6630004/203f8766-c8d1-11e4-8d78-453b55f33cb1.png)

**Comment by xmatthewx** [comment]
Great resources. 

Beyond touch targets, I just want to make sure we don't squeeze the tile canvas too small.

![percent-canvas](https://cloud.githubusercontent.com/assets/53411/6641086/023de9c8-c972-11e4-89b5-096bbe4ed8ac.png)

 A taller, mobile-friendly tile will squeeze this even further. Regardless of resolution, we just need to stay mindful of how these proportions impact screen real-estate.

**Comment by xmatthewx** [comment]
cc @vazquez - doesn't impact mobile. something to keep in mind when we work on desktop later in the year.
