### ISSUE TITLE
Forward traffic from Webmaker.org

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#90]
Details here: https://github.com/mozilla/webmaker.org/issues/1419

**Comment by jbuck** [comment]
@thisandagain This patch is landed and ready to go to production, just need to run the jenkins job: https://jenkins.mofoprod.net/job/PRODPUSH-webmakerorg/

If you don't have a jenkins account @cadecairos can help you out!

**Comment by xmatthewx** [comment]
Is there any reason we didn't start forwarding traffic @thisandagain? 

@cadecairos -  if you can lend a hand, I think we should do this.  I know that @hannahkane and others would like to put the new Maker Party promo in front of more eyes.

**Comment by cadecairos** [comment]
I can prod push it, if we all agree it's time

**Comment by xmatthewx** [comment]
@HPaulJohnson - Are you ready for wm.org traffic to forward to beta? (Landing page only)

cc: @adamlofting

**Comment by xmatthewx** [comment]
cc @secretrobotron

**Comment by HPaulJohnson** [comment]
@xmatthewx - yes!

**Comment by secretrobotron** [comment]
:rocket:

**Comment by cadecairos** [comment]
All done!

https://webmaker.org
