### ISSUE TITLE
Redirect share links appropriately on desktop

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-desktop#91]
From #69:
Proposal:
- User-agent detect
- If Android:
  - Redirect to deep link `webmaker://play` etc.
- If Other:
  - Show player if landed. If not:
  - Redirect to Google Play store

Platform scenarios mapped here: https://github.com/mozilla/webmaker-android/issues/1616#issuecomment-101424066

**Comment by secretrobotron** [comment]
cc @HPaulJohnson @xmatthewx @thisandagain

**Comment by thisandagain** [comment]
Tracking in #62
